backend/urls.py
from django.urls import path
from backend import views


app_name = 'backend'

urlpatterns = [
    path('', views.login_view, name='login_view'),
    path('dashboard-page/', views.dashboard, name='dashboard'),
    path('list1-page/', views.list1, name='list1'),
    path('category-page/', views.category, name='category'),
    path('confirm-logout/', views.confirm_logout, name='confirm_logout'),
    path('logout_view/', views.logout_view, name='logout_view')
]
    

first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from frontend import views
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('', views.index, name='index'),
    path('pages/', include('frontend.urls')),
    path('backend/', include('backend.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
 urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
 urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

frontend/urls.py
from django.urls import path
from frontend import views

app_name = 'frontend'

urlpatterns = [
    path('', views.about, name='about'),
    path('detail/<int:abt_id>/', views.about_detail, name = 'about_detail'),
    path('detail/<int:phn_id>/', views.product_detail, name = 'product_detail'),
    path('contact-page/', views.contact, name='contact'),  
    path('phone-page/', views.phone, name='product-list1'), 
    path('laptop-page/', views.laptop, name='product-list2'), 
    path('detail-page/', views.detail, name='product-detail'), 
]

backend/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    cat_name = models.CharField(max_length=100, verbose_name='Category Name')
    name = models.CharField(max_length=150)
    cat_desc = models.TextField(blank=True, null=True, verbose_name='Description')
    profile = models.FileField(null=True, blank=True, upload_to='uploads/')
    def __str__(self):
            return self.name
            
    def __str__(self):
        return self.cat_name
    
    class Meta():
        verbose_name_plural = 'Category'

    def profile_img(self):
          if self.profile:
              return self.profile.url
            

frontend/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    age = models.PositiveIntegerField()
    website = models.URLField(blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.user.username

class Category(models.Model):
    cat_name = models.CharField(max_length=100, verbose_name='Category Name')
    cat_desc = models.TextField(blank=True, null=True, verbose_name='Description')

    def __str__(self):
        return self.cat_name
    
    class Meta():
        verbose_name_plural = 'Post Category'

    




class Post(models.Model):
    pst_title = models.CharField(max_length=150, verbose_name='Post Title')
    pst_image = models.FileField(null=True, blank=True, upload_to='uploads/')
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cat_id = models.ManyToManyField(Category, verbose_name='Category')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.pst_title

    class Meta():
        verbose_name_plural = 'Post'


class About(models.Model):
      profile = models.FileField(null=True, blank=True, upload_to='uploads/')
      name = models.CharField(max_length=150)
      content = models.TextField()

      def __str__(self):
            return self.name

      class Meta():
            verbose_name_plural = 'About'



      def profile_img(self):
          if self.profile:
              return self.profile.url


class Products(models.Model):
      profile = models.FileField(null=True, blank=True, upload_to='uploads/')
      name = models.CharField(max_length=150)
      content = models.TextField()
      price =  models.PositiveIntegerField()

      def __str__(self):
            return self.name

      class Meta():
            verbose_name_plural = 'products'



      def profile_img(self):
          if self.profile:
              return self.profile.url
            
            

backend/views.py
from django.shortcuts import render, redirect


from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from backend.models import *

# Create your views here.

def login_view(request):
    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request,user)
            return redirect('backend:dashboard')
        else:
            messages.error(request, 'Username and Password do not match')
    return render(request, 'backend/login.html')

@login_required(login_url ='/dashboard')
def dashboard(request):
    return render(request, 'backend/admin.html')

def list1(request):
    return  render(request,'backend/view-products.html')

def category(request):
    category=Category.objects.all()
    return  render(request,'backend/category.html', {'phn':category})

    
@login_required(login_url ='/dashboard')
def confirm_logout(request):
    return render(request, 'backend/confirm-logout.html')

@login_required(login_url ='/dashboard')
def logout_view(request):
    return redirect('backend:logout_view')

frontend/views.py
from django.shortcuts import render
from django.http import HttpResponse
from frontend.models import *

# Create your views here.
def index(request):
    return  render(request,'frontend/index.html')

def phone(request):
    products=Products.objects.all()
    return  render(request,'frontend/product-list1.html',{'phn':products})

def laptop(request):
    return  render(request,'frontend/product-list2.html')

def detail(request):
    return  render(request,'frontend/product-detail.html')

def about(request):
    about=About.objects.all()
    return render(request, 'frontend/about.html', {'abt': about})


def about_detail(request, abt_id):
    detail = About.objects.get(id = abt_id)
    return render(request, 'frontened/about-detail.html',{'det':detail})

def product_detail(request, phn_id):
    detail = Products.objects.get(id = phn_id)
    return render(request, 'frontened/product-detail.html',{'phn':detail})




def contact(request):
    return render(request, 'frontend/contact.html')

templates/backend/admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin</title>
    <link href="{% static 'backend/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'backend/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'backend/css/admin.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  {% block content %}

      {% endblock %}

  <body id="admin">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3" id="top-sidebar">
          <img src="{% static 'backend/images/admin-logo.png' %}" class="img-responsive">
        </div>
        <div class="col-sm-9" id="top-content">
         <div class="status pull-right">
           <div class="userStatus">
            <img src="{% static 'backend/images/About 2.jpg' %}" class="img-circle" height="50">
             <a class="userStatus dropdown-toggle" data-toggle="dropdown" id="userStatus">
              {{ request.user.username }}
                  <span class="caret"></span>
             </a>
             <span class="dropdown-menu pull-right">
              <a href="{% url 'backend:confirm_logout' %}">Log Out</a><br>
              <a href="change-password.php">Change Password</a><br>
              <a href="edit-profile.php">Edit Profile</a>
             </span>
           </div>
         </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3" id="adim-sidebar">
          <div class="row">
            <div class="col-sm-3">
              <a href="admin.html">
                <img src="{% static 'backend/images/admin-logo.png' %}" class="img-responsive">
              </a>
            </div>
            <div class="col-sm-9">
              <span>{{ request.user.username }}</span><br>
              <span class="fa fa-circle text-success"></span>
              Online<br>
            </div>
          </div>
          <div class="panel-group" id="accordion">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                   <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
                     Users
                     <span class="pull-right"> 
                       <span class="fa fa-angle-left"></span>
                     </span>
                   </a>
                </h4>
              </div>
              <div id="collapse1" class="panel-collapse collapse in">
                <div class="panel-body">
                  <ul class="nav">
                    <li>
                      <a href="#">
                        <span class="fa fa-circle-o"></span>
                         Add Users
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <span class="fa fa-circle-o"></span>
                        View Users
                      </a>
                    </li> 
                   
                  </ul>
                </div>
              </div>
            </div>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                   <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
                     Products
                     <span class="pull-right"> 
                       <span class="fa fa-angle-left"></span>
                     </span>
                   </a>
                </h4>
              </div>
              <div id="collapse2" class="panel-collapse collapse in">
                <div class="panel-body">
                  <ul class="nav">
                    <li>
                      <a href="#">
                        <span class="fa fa-circle-o"></span>
                         Add Products
                      </a>
                    </li>
                    <li>
                      <a href="{% url 'backend:list1' %}">
                        <span class="fa fa-circle-o"></span>
                        View Products
                      </a>
                    </li> 
                    <li>
                      <a href="#">
                        <span class="fa fa-circle-o"></span>
                        Categories
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            
          </div>
        </div>
        <div class="col-sm-9" id="admin-main-content">
          <div class="col-sm-4">
           <div class="inner-box">
             <a href=""> 
              <i class="fa fa-users"></i> 
              <span>10</span>
              <h4> Posts</h4>
             </a>
           </div>
          </div> 
          <div class="col-sm-4">
           <div class="inner-box">
             <a href="{% url 'backend:category' %}"> 
              <i class="fa fa-male"></i> 
               <span>5</span>
               <h4> Categories</h4>
               <span class="little-text"></span>
             </a>
           </div>
          </div> 
          <div class="col-sm-4">
           <div class="inner-box">
             <a href=""> 
              <i class="fa fa-users"></i> 
              <span>15</span>
              <h4>Users</h4>
              <span class="little-text">Subscribers</span>
             </a>
           </div>
          </div>
        </div>
      </div>

    </div>



   




    
    <script src="{% static 'backend/js/jquery.js' %}"></script>
    <script src="{% static 'backend/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/backend/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      {% block title %}

       {% endblock %}
    </title>
    <link href="{% static 'backend/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'backend/css/custom-fonts.css' %}" rel="stylesheet">
    <link href="{% static 'backend/css/login.css' %}" rel="stylesheet">
    <link href="{% static 'backend/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% block content %}

      {% endblock %}



    
    <script src="{% static 'frontend/js/jquery.js' %}"></script>
    <script src="{% static 'frontend/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/backend/category.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin</title>
    <link href="{% static 'backend/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'backend/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'backend/css/admin.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  {% block content %}
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3" id="top-sidebar">
          <img src="{% static 'backend/images/admin-logo.png' %}" class="img-responsive">
        </div>
        <div class="col-sm-9" id="top-content">
         <div class="status pull-right">
           <div class="userStatus">
            <img src="{% static 'backend/images/About 2.jpg' %}" class="img-circle" height="50">
             <a class="userStatus dropdown-toggle" data-toggle="dropdown" id="userStatus">
              {{ request.user.username }}
                  <span class="caret"></span>
             </a>
             <span class="dropdown-menu pull-right">
              <a href="logout.php">Log Out</a><br>
              <a href="change-password.php">Change Password</a><br>
              <a href="edit-profile.php">Edit Profile</a>
             </span>
           </div>
         </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3" id="adim-sidebar">
          <div class="row">
            <div class="col-sm-3">
              <a href="admin.html">
                <img src="{% static 'backend/images/admin-logo.png' %}" class="img-responsive">
              </a>
            </div>
            <div class="col-sm-9">
              <span>{{ request.user.username }}</span><br>
              <span class="fa fa-circle text-success"></span>
              Online<br>
            </div>
          </div>
          <div class="panel-group" id="accordion">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                   <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
                     Users
                     <span class="pull-right"> 
                       <span class="fa fa-angle-left"></span>
                     </span>
                   </a>
                </h4>
              </div>
              <div id="collapse1" class="panel-collapse collapse in">
                <div class="panel-body">
                  <ul class="nav">
                    <li>
                      <a href="#">
                        <span class="fa fa-circle-o"></span>
                         Add Users
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <span class="fa fa-circle-o"></span>
                        View Users
                      </a>
                    </li> 
                   
                  </ul>
                </div>
              </div>
            </div>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                   <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
                     Products
                     <span class="pull-right"> 
                       <span class="fa fa-angle-left"></span>
                     </span>
                   </a>
                </h4>
              </div>
              <div id="collapse2" class="panel-collapse collapse in">
                <div class="panel-body">
                  <ul class="nav">
                    <li>
                      <a href="#">
                        <span class="fa fa-circle-o"></span>
                         Add Products
                      </a>
                    </li>
                    <li>
                      <a href="{% url 'backend:list1' %}">
                        <span class="fa fa-circle-o"></span>
                        View Products
                      </a>
                    </li> 
                    <li>
                      <a href="#">
                        <span class="fa fa-circle-o"></span>
                        Categories
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            
          </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-sm-8">
               <div class="row">
                 {% if phn %}
                  {% for a in phn %}
                <div class="col-sm-4">
                      <img src="{{ a.profile_img}}" class="img-thumbnail">
                  <h2>{{a.name}}</h2>
                  <p>
                    {{ phn.content }}
                   </p>
                </div>
              {% endfor %}
            {% endif%}    
               </div>
 {% endblock %}

templates/backend/confirm-logout.html
{% extends 'backend/base.html' %}
{% load static %}
<!DOCTYPE html>
{% block title %}
Dashboard
{% endblock %}

{% block content %}
<body id="admin">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3" id="top-sidebar">
          <img src="{% static 'backend/images/admin-logo.png' %}" class="img-responsive">
        </div>
        <div class="col-sm-9" id="top-content">
         <div class="status pull-right">
           <div class="userStatus">
            <img src="{% static 'backend/images/About 2.jpg' %}" class="img-circle" height="50">
             <a class="userStatus dropdown-toggle" data-toggle="dropdown" id="userStatus">
              {{ request.user.username }}
                  <span class="caret"></span>
             </a>
             <span class="dropdown-menu pull-right">
              <a href="{% url 'backend:confirm_logout' %}">Log Out</a><br>
              <a href="change-password.php">Change Password</a><br>
              <a href="edit-profile.php">Edit Profile</a>
             </span>
           </div>
         </div>
        </div>
      </div>

<h2 class="text-center">LOG OUT</h2>
<p class="text-center">Do you really want to logout</p>
<h4 class="text-center"><a href="{% url 'backend:login_view' %}">Logout</a></h4>

{% endblock %}

templates/frontend/about-detail.html
{% extends 'frontend/base.html' %}
{% load static %}
<!Doctype html>
{% block title %}
Detail
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-8 col-sm-8">
     <div class="row">
       <div class="blog-content">
         <div class="col-sm-12 single-blog">
          {% if det %}
           <img src="{{ det.profile_imd }}" class="img-thumbnail img-responsive">
         </div>
         <div class="col-sm-12">
           <h2>{{ det.name }}</h2>
           <p>
            {{ det.content }}
           </p>
         </div>
         {% endif %}
       </div>
     </div>
   
  


{% endblock %}

  




    
   

templates/frontend/about.html
{% extends 'frontend/base.html' %}
{% load static %}
<!DOCTYPE html>
{% block title %}
About
{% endblock %}
{% block content %}
 <!-- SITE BLOG STARTS HERE -->
 <div class="row">
    <div class="col-md-8 col-sm-8">
       <div class="row">
         {% if abt %}
          {% for a in abt %}
        <div class="col-sm-4">
          <a href="about-detail.html">
              <img src="{{ a.profile_img}}" class="img-circle">
          </a>
          <h2>{{a.name}}</h2>
          <a href="{% url 'frontend:about_detail' a.id %}" class="btn btn-primary">Readmore</a>
        </div>
      {% endfor %}
    {% endif%}    
       </div>
     
    
    </div>
    <div class="col-md-4 col-sm-4">
      <div class="widget">
        <h3>Categories</h3>
        <ul class="nav">
          <li><a href="#">Sports</a></li>
          <li><a href="#">Politics</a></li>
          <li><a href="#">Entertainment</a></li>
          <li><a href="#">User</a></li>
        </ul>
      </div>
       <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
           <form class="form-inline">
           <input class="form-control mr-sm-8" type="text" placeholder="Search">
           <button class="btn btn-success" type="submit">Search</button>
       </form>
      </nav>
      <div class="widget">
        <h3>Email Subscribtion</h3>
        <form class="form">
          <div class="form-group">
            <input type="text" name="email" class="form-control" placeholder="Enter Email">
          </div>
          <input type="submit" name="submit" class="btn btn-default btn-block">
        </form>
      </div>
    </div>
  </div>
  <!-- SITE BLOG ENDS HERE -->
{% endblock %}

templates/frontend/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link href="{% static 'frontend/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/font-awesome.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="container-fluid" id="top-info">
      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
             data-target="#infoTop">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span> 
            </button>
          </div>
          <div class="collapse navbar-collapse" id="infoTop">
            <span class="contact-info">
              <span class="contact-group">
                  <span class="fa fa-phone"></span>
                  <span class="contact-text">
                    08157550744
                  </span>
              </span>
              <span class="contact-group">
                  <span class="fa fa-envelope"></span>
                  <span class="contact-text">
                    youremail@domain.com
                  </span>
              </span>
              <span class="contact-group">
                  <span class="fa fa-map-marker"></span>
                  <span class="contact-text">
                    No, 12 Oluakerele
                  </span>
              </span>
            </span>
            <span class="contact-info pull-right">
              <span class="contact-group">
                  <span class="fa fa-user"></span>
                  <a href="#" class="contact-text">
                    Sign Up
                  </a>
              </span>
              <span class="contact-group">
                  <span class="fa fa-sign-in"></span>
                  <a href="{% url 'backend:login_view' %}" class="contact-text">
                    Login
                  </a>
              </span>
            </span>
          </div>
        </div>
      </div>
    </div>
    <!-- END OF TOP INFO -->
    <div class="container" id="main-content">
      <div class="row">
        <div class="col-md-3 col-sm-3">
          <img src="{% static 'frontend/images/logo.png' %}">
        </div>
        <div class="col-md-9 col-sm-9">
          <span class="social-icon pull-right">
            <a href="#" target="_blank">
              <img src="{% static 'frontend/images/fb.png' %}" class="img-circle">
            </a>
            <a href="#" target="_blank">
              <img src="{% static 'frontend/images/gp.png' %}" class="img-circle">
            </a>
            <a href="#" target="_blank">
              <img src="{% static 'frontend/images/tw.png' %}" class="img-circle">
            </a>
          </span>
        </div>
      </div>
      <!-- END OF SITE LOGO -->
      <div class="row">
        <div class="navbar navbar-inverse" id="main-nav">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#site-nav">
                <span class="fa fa-arrow-down ">menu</span>
              </button>
            </div>
            <div class="collapse navbar-collapse" id="site-nav">
              <ul class="nav navbar-nav">
                <li><a href="{% url 'index' %}" class="">Home</a></li>
                <li><a href="{% url 'frontend:about' %}">About</a></li>
                <li><a href="{% url 'frontend:product-list1' %}">Phones</a></li>
                <li><a href="{% url 'frontend:product-list2' %}">Laptops</a></li>
                <li><a href="#">Shirts</a></li>
                <li><a href="#">Screens</a></li>
                <li><a href="{% url 'frontend:contact' %}">Contact</a></li>

              </ul>
            </div>
          </div>
        </div>
      </div>
      <!-- END OF SITE MENU -->
      {% block content %}

      {% endblock %}
     <div class="row">
        
    <!-- END OF MAIN CONTENT -->
    <div class="container-fluid" id="site-footer">
      <div class="row">
        <div class="col-md-3 col-sm-6">
          <h4>Services</h4>
          <ul class="nav">
            <li><a href="#">Web Development</a></li>
            <li><a href="#">Mobile App Development</a></li>
            <li><a href="#">Software Development</a></li>
            <li><a href="#">Graphic Design</a></li>
          </ul>
        </div>
        <div class="col-md-3 col-sm-6">
          <h4>Links</h4>
          <ul class="nav">
            <li><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Services</a></li>
          </ul>
        </div>
        <div class="col-md-3 col-sm-6">
          <h4>Subscribe</h4>
          <form class="form">
            <div class="form-group">
              <input type="text" name="email" class="form-control">
            </div>
            <input type="submit" name="submit" value="Subscribe" class="btn btn-default btn-block">
          </form>
        </div>
        <div class="col-md-3 col-sm-6">
          <h4>Follow Us</h4>
          <span class="social-icon">
            <a href="#" target="_blank">
              <img src="{% static 'frontend/images/fb.png' %}" class="img-circle">
            </a>
            <a href="#" target="_blank">
              <img src="{% static 'frontend/images/gp.png' %}" class="img-circle">
            </a>
            <a href="#" target="_blank">
              <img src="{% static 'frontend/images/tw.png' %}" class="img-circle">
            </a>
          </span>
        </div>

      </div>
    </div>
    
    <script src="{% static 'frontend/js/jquery.js' %}"></script>
    <script src="{% static 'frontend/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/frontend/product-list1.html
{% extends 'frontend/base.html' %}
{% load static %}
<!DOCTYPE html>
{% block title %}
Phone
{% endblock %}
{% block content %}
 <!-- SITE BLOG STARTS HERE -->
 <div class="row">
    <div class="col-md-8 col-sm-8">
       <div class="row">
         {% if phn %}
          {% for a in phn %}
        <div class="col-sm-4">
          <a href="product-detail.html">
              <img src="{{ a.profile_img}}" class="img-thumbnail">
          </a>
          <h2>{{a.name}}</h2>
          <a href="{% url 'frontend:product_detail' a.id %}" class="btn btn-primary">Readmore</a>
        </div>
      {% endfor %}
    {% endif%}    
       </div>
     
    
    </div>
    <div class="col-md-4 col-sm-4">
      <div class="widget">
        <h3>Categories</h3>
        <ul class="nav">
          <li><a href="#">Sports</a></li>
          <li><a href="#">Politics</a></li>
          <li><a href="#">Entertainment</a></li>
          <li><a href="#">User</a></li>
        </ul>
      </div>
       <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
           <form class="form-inline">
           <input class="form-control mr-sm-8" type="text" placeholder="Search">
           <button class="btn btn-success" type="submit">Search</button>
       </form>
      </nav>
      <div class="widget">
        <h3>Email Subscribtion</h3>
        <form class="form">
          <div class="form-group">
            <input type="text" name="email" class="form-control" placeholder="Enter Email">
          </div>
          <input type="submit" name="submit" class="btn btn-default btn-block">
        </form>
      </div>
    </div>
  </div>
  <!-- SITE BLOG ENDS HERE -->
{% endblock %}